// <auto-generated />
using Lab3APInet21;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab3APInet21.Migrations
{
    [DbContext(typeof(DataRegisterDb))]
    partial class DataRegisterDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab3APInet21.Models.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyId");

                    b.HasIndex("PersonId");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            HobbyId = 1,
                            Description = "Make them Shine",
                            PersonId = 1,
                            Titel = "Cars"
                        },
                        new
                        {
                            HobbyId = 2,
                            Description = "Make them Fast",
                            PersonId = 2,
                            Titel = "Cars"
                        },
                        new
                        {
                            HobbyId = 3,
                            Description = "Teleports",
                            PersonId = 5,
                            Titel = "Magic"
                        },
                        new
                        {
                            HobbyId = 4,
                            Description = "Lightning",
                            PersonId = 4,
                            Titel = "Magic"
                        },
                        new
                        {
                            HobbyId = 5,
                            Description = "Train Legs",
                            PersonId = 2,
                            Titel = "WorkOut"
                        },
                        new
                        {
                            HobbyId = 6,
                            Description = "Train Arms",
                            PersonId = 3,
                            Titel = "WorkOut"
                        },
                        new
                        {
                            HobbyId = 7,
                            Description = "Make them Weird",
                            PersonId = 5,
                            Titel = "Cars"
                        },
                        new
                        {
                            HobbyId = 8,
                            Description = "Calculate stuff",
                            PersonId = 1,
                            Titel = "Math"
                        });
                });

            modelBuilder.Entity("Lab3APInet21.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Name = "Tony",
                            PhoneNumber = "0701231233"
                        },
                        new
                        {
                            PersonId = 2,
                            Name = "Banner",
                            PhoneNumber = "070321321"
                        },
                        new
                        {
                            PersonId = 3,
                            Name = "Rogers",
                            PhoneNumber = "0703123123"
                        },
                        new
                        {
                            PersonId = 4,
                            Name = "Thor",
                            PhoneNumber = "0704141444"
                        },
                        new
                        {
                            PersonId = 5,
                            Name = "Strange",
                            PhoneNumber = "0705555112"
                        });
                });

            modelBuilder.Entity("Lab3APInet21.Models.WebbLink", b =>
                {
                    b.Property<int>("WebbLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebbLinkId");

                    b.HasIndex("HobbyId");

                    b.ToTable("WebbLinks");

                    b.HasData(
                        new
                        {
                            WebbLinkId = 1,
                            HobbyId = 1,
                            Link = "FakeLinkForHobby1"
                        },
                        new
                        {
                            WebbLinkId = 2,
                            HobbyId = 2,
                            Link = "FakeLinkForHobby1"
                        },
                        new
                        {
                            WebbLinkId = 3,
                            HobbyId = 3,
                            Link = "FakeLinkForHobby2"
                        },
                        new
                        {
                            WebbLinkId = 4,
                            HobbyId = 4,
                            Link = "FakeLinkForHobby2"
                        },
                        new
                        {
                            WebbLinkId = 5,
                            HobbyId = 5,
                            Link = "FakeLinkForHobby3"
                        },
                        new
                        {
                            WebbLinkId = 6,
                            HobbyId = 6,
                            Link = "FakeLinkForHobby3"
                        },
                        new
                        {
                            WebbLinkId = 7,
                            HobbyId = 7,
                            Link = "FakeLinkForHobby4"
                        },
                        new
                        {
                            WebbLinkId = 8,
                            HobbyId = 8,
                            Link = "FakeLinkForHobby4"
                        });
                });

            modelBuilder.Entity("Lab3APInet21.Models.Hobby", b =>
                {
                    b.HasOne("Lab3APInet21.Models.Person", "Person")
                        .WithMany("Hobbies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab3APInet21.Models.WebbLink", b =>
                {
                    b.HasOne("Lab3APInet21.Models.Hobby", "Hobby")
                        .WithMany("WebbLinks")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
